# The non prompting deploy config for ./config-templates.py
context:
  namespace: default
  cluster_name: escluster
  data_node:
    replicas: 2
    storage_class: standard
    heap_size: 512m
    memory_limit: 1Gi
    volume_size: 250
  skip_logstash: false
  skip_oauth: true
  logstash_beats_port: 8751
  logstash_python_log_hndlr_port: 5959
ssl:
  ca_name: Logstash CA
  common_name: logstash
  country: US
  state: CA
  loc: Los Angeles
  org: ACME
  org_unit: Pipeline