# The non prompting deploy config for ./config-templates.py
escluster:
  namespace: default
  cluster_name: escluster
  skip_logstash: false
  skip_oauth: true
  esnodes:
    data_node_replicas: 2
    storage_class: standard
    heap_size: 512m
    memory_limit: 1Gi

logstash:
  enabled: true
  beats_port: 8751
  python_log_handler_port: 5959
  ssl:
    ca_name: Logstash CA
    common_name: logstash
    country: US
    state: CA
    loc: Los Angeles
    org: ACME
    org_unit: Pipeline