apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ namespace }}
  name: logstash-pipelines
data:
{% macro inc(str) %}{% include str %}{% endmacro %}
  python-logs.conf: |
{{ inc('6_logstash/conf.d/python-logs.conf')|indent(first=true) }}
  logstash.conf: |
{{ inc('6_logstash/conf.d/logstash.conf')|indent(first=true) }}
